### ISSUE TITLE
Crash when in level

### ISSUE THREAD

**Issue by ghost** [zkayns/EclipseMenu#3]
2024-07-10T19:05:08-0400
Whoopsies! An unhandled exception has occurred.

== Geode Information ==
Loader Version: v3.2.0
Loader Commit: 65ed0d4
Bindings Commit: 103fbd9
Installed mods: 22
Problems: 14

== Exception Information ==
C++ Exception: class nlohmann::json_abi_v3_11_3::detail::type_error("[json.exception.type_error.302] type must be boolean, but is number")
Faulty Mod: Eclipse v1.0.0 (eclipse.eclipse-menu)
Crashed thread: Main

== Stack Trace ==
 - C:\Windows\System32\KERNELBASE.dll + 5f39c (RaiseException + 108)
 - C:\Windows\SYSTEM32\VCRUNTIME140.dll + 6ba7 (CxxThrowException + 151)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 1350f
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 588b3
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 2ba6a
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 2b896
 - 000001B64709A872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 131170
 - 000001B64709A872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 131170
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 5f06b
 - 000001B64709A872 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 205418
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 2281b7
 - 000001B64709E472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 12c91b
 - 000001B64709E472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 12c91b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 57a34
 - 000001B64709E472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 12c91b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 43efd
 - 000001B64709E472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + c041d (cocos2d::CCScheduler::update + 141)
 - 000001B647094472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + ad84a
 - 000001B647094472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 7f83c
 - 000001B647094472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 2d114
 - 000001B647094472 (Hook handler)
 - 000001B647094472 (Hook handler)
 - 000001B647094472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\geode\unzipped\eclipse.eclipse-menu\eclipse.eclipse-menu.dll + 5c6b4
 - 000001B647094472 (Hook handler)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bbc24 (cocos2d::CCDirector::drawScene + 36)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + bc33b
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\libcocos2d.dll + 72cd2 (cocos2d::CCApplication::run + 1122)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a2d69
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\Geode.dll + 23a41a (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Program Files (x86)\Steam\steamapps\common\Geometry Dash\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 1257d (BaseThreadInitThunk + 29)
 - C:\Windows\SYSTEM32\ntdll.dll + 5af28 (RtlUserThreadStart + 40)

== Register States ==
RAX: 00007ff8f9dcc350
RBX: 0000000000000000
RCX: 000001b600000002
RDX: 00007ff800000004
RBP: 0000000000000000
RSP: 000000252ed7fac0
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ff8f9deaf28
R8:  00007ff8000001f2
R9:  000001b604eff2e0
R10: 000001b603b2eee0
R11: 000001b604b7cee0
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
! | [v1.1.0] alphalaneous.ezclipboard
! | [v1.3.0] alphalaneous.happy_textures
! | [v1.1.0] alphalaneous.random_tab
x | [v4.2.0-beta.3] cvolton.betterinfo
x | [v1.2.0-beta.1] cvolton.misc_bugfixes
! | [v1.3.7] dankmeme.globed2
x | [v1.0.0] eclipse.eclipse-menu
! | [v1.0.5] firee.goldenbest
! | [v1.7.2] firee.prism
! | [v2.10.0-beta.4] fleym.nongd
! | [v1.6.0-beta.1] geode.custom-keybinds
x | [v3.2.0] geode.loader
x | [v1.13.1] geode.node-ids
x | [v1.2.7] hiimjustin000.fake_rate
  | [v6.4.3] hjfod.betteredit
! | [v1.3.0] hjfod.bettersave
! | [v1.1.0] hjfod.gmd-api
! | [v1.1.0] polsk.ratinginfo
! | [v1.1.2] rynat.better_unlock_info
  | [v1.4.4-beta.5] thesillydoggo.qolmod
! | [v1.6.8] tpdea.betterpause-Better
! | [v1.4.1] uproxide.more_difficulties

**Comment by zkayns** [comment]
yeah this happens sometimes and im pretty confident its a bug with the saving system, my only solution is to delete config.json in the mod's save directory

**Comment by ghost** [comment]
tried and after opening the menu for a few secs it crashed

**Comment by ghost** [comment]
nvm had to update
